project:
  type: website

website:
  title: "What 90+ Open-Source PRs Taught Me About Software Quality and Engineering at Scale"
  site-url: "https://yourusername.github.io/your-repo-name"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 3
    contents:
      - section: "What 90+ Open-Source PRs Taught Me About Software Quality and Engineering at Scale"
        contents:
          - text: "Turning PRs into Data"
            href: index.qmd#turning-prs-into-data
          - text: "Why Contributing at Scale Matters in Open Source"
            href: index.qmd#why-contributing-at-scale-matters-in-open-source
          - text: "Featured Contributions and Recognition"
            href: index.qmd#featured-contributions-and-recognition
          - text: "Good Practices While Contributing"
            href: index.qmd#good-practices-while-contributing
          - text: "Reflections for Future Contributions"
            href: index.qmd#reflections-for-future-contributions
      - section: "About"
        contents:
          - href: about.qmd
            text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true