project:
  type: website

website:
  title: "What 90+ Open-Source PRs Taught Me About Software Quality and Engineering at Scale"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 3
    contents:
      - section: "About"
        contents:
          - href: index.qmd
            text: About
      - section: "What 90+ Open-Source PRs Taught Me About Software Quality and Engineering at Scale"
        contents:
          - text: "Turning PRs into Data"
            href: turning-prs-into-data.qmd
          - text: "Why Contributing at Scale Matters in Open Source"
            href: why-contributing-matters.qmd
          - text: "Featured Contributions and Recognition"
            href: featured-contributions.qmd
          - text: "Good Practices While Contributing"
            href: good-practices.qmd
          - text: "Reflections for Future Contributions"
            href: reflections.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true